from typing import Any

class Broadcast:
    """Broadcast facade."""

    def add_driver(name: str, driver: Any): ...
    def set_configuration(config: dict) -> "Broadcast": ...
    def get_driver(name: str = None) -> Any: ...
    def get_config_options(driver: str = None) -> dict: ...
    def channel(channels, event=None, value=None, driver=None) -> None: ...
    @classmethod
    def routes(auth_route: str = "/broadcasting/authorize") -> list: ...
