from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ..mail import Mailable

class Mail:
    """Mail facade."""

    def add_driver(self, name: str, driver: Any): ...
    def set_configuration(self, config: dict) -> "Mail": ...
    def get_driver(self, name: str = None) -> Any: ...
    def get_config_options(self, driver: str = None) -> dict: ...
    def mailable(self, mailable: "Mailable") -> "Mail": ...
    def send(self, driver: str = None): ...
