from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ..mail import Mailable

class Mail:
    """Mail facade used to send emails from your application."""

    def add_driver(name: str, driver: Any): ...
    def set_configuration(config: dict) -> "Mail": ...
    def get_driver(name: str = None) -> Any: ...
    def get_config_options(driver: str = None) -> dict: ...
    def mailable(mailable: "Mailable") -> "Mail":
        """Define the mailable to be sent before calling send()."""
        ...
    def send(driver: str = None):
        """Send e-mail from your application with the given driver (or default driver)."""
        ...
