from typing import Any

class Queue:
    def add_driver(self, name: str, driver: str): ...
    def get_driver(self, name: str) -> Any: ...
    def set_configuration(self, config: dict) -> "Queue": ...
    def get_config_options(self, driver: str) -> dict: ...
    def push(self, *jobs, **options) -> None: ...
    def consume(self, options: dict) -> Any: ...
    def retry(self, options: dict) -> Any: ...
