from typing import Any

class Storage:
    """File storage facade."""

    def add_driver(self, name: str, driver: str): ...
    def set_configuration(self, config: dict) -> "Storage": ...
    def get_driver(self, name: str = None) -> Any: ...
    def get_config_options(self, name: str = None) -> dict: ...
    def disk(self, name: str = "default") -> Any:
        """Get the file manager instance for the given disk name."""
        ...