"""Metadata for Masonite package."""
__title__ = "masonite"
__description__ = "The core for the Masonite framework"
__url__ = "https://github.com/MasoniteFramework/masonite"
__version__ = "3.0.7"
__author__ = "Joseph Mancuso"
__author_email__ = "joe@masoniteproject.com"
__licence__ = "MIT"

__cookie_cutter_version__ = "3.0"
