name: Test Application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          make ci
      - name: Test with pytest
        env:
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          DB_CONFIG_PATH: tests/integrations/config/database
        run: |
          make ci-test
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v6
      - name: Set up latest Python 3.X
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install Flake8
        run: |
          pip install flake8
      - name: Lint
        run: make lint
